spring:
  data:
    cassandra:
      keyspace-name: sakila
      schema-action: create_if_not_exists
      port: 9042
      consistency-level: each_quorum
  datasource:
    url: jdbc:mysql://localhost:3306/sakila?serverTimezone=UTC
    username: root
    password: root
  jpa:
    database: mysql
